import { Tutor, Appointment, AppNotification, Manager } from './types';
import { format, startOfWeek, addDays } from 'date-fns';

export const INITIAL_MANAGERS: Manager[] = [
  {
    id: 'mgr-admin',
    name: 'Руководитель школы (Администратор)',
    email: 'admin@sto-pyaterok.ru',
    phone: '+7 (999) 111-22-33',
    role: 'admin',
    active: true,
    createdAt: '2025-01-10',
  },
  {
    id: 'mgr-1',
    name: 'Елена Васильева',
    email: 'elena@sto-pyaterok.ru',
    phone: '+7 (926) 400-12-34',
    role: 'manager',
    active: true,
    createdAt: '2025-09-01',
  },
  {
    id: 'mgr-2',
    name: 'Михаил Соколов',
    email: 'mikhail@sto-pyaterok.ru',
    phone: '+7 (926) 500-56-78',
    role: 'manager',
    active: true,
    createdAt: '2025-11-15',
  },
];

export const TUTORS: Tutor[] = [
  {
    "experienceYears": 9,
    "availableDays": [
      2,
      3,
      4,
      5,
      6
    ],
    "achievements": [
      "Средний балл учеников по русскому языку в 2025 году — 89.2",
      "22 ученика сдали ЕГЭ на 95+ баллов",
      "Разработчик интенсива по идеальному сочинению (критерий К1-К12 на 100%)",
      "Финалист всероссийского конкурса «Педагогический дебют»"
    ],
    "bio": "Филолог, автор методики ускоренной подготовки к тестовой части за 2 месяца.",
    "salesConversionRate": 88,
    "rating": 4.98,
    "tag": "Лидер доходимости ⭐",
    "telegram": "@asiyat_rus",
    "id": "tutor-2",
    "color": "indigo",
    "education": "СПбГУ, Филологический факультет, красный диплом",
    "name": "Асият Асхатовна Шаваева",
    "phone": "+7 (912) 345-67-82",
    "shortName": "Асият Шаваева",
    "subjects": [
      "Русский язык",
      "Литература",
      "Сочинение ЕГЭ"
    ],
    "activeStudents": 18,
    "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80"
  },
  {
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    "shortName": "Татьяна Блинова",
    "color": "rose",
    "telegram": "@tatiana_eng",
    "achievements": [
      "Сертификат Cambridge CELTA Grade A (преподавание международного уровня)",
      "18 учеников поступили в зарубежные и топовые российские вузы (МГИМО, ВШЭ)",
      "Автор курса преодоления языкового барьера для подростков"
    ],
    "education": "МГЛУ им. Мориса Тореза, Международный сертификат Cambridge CELTA",
    "subjects": [
      "Английский язык",
      "ОГЭ/ЕГЭ",
      "Разговорный"
    ],
    "tag": "Топ конверсий 🔥",
    "phone": "+7 (912) 345-67-84",
    "salesConversionRate": 82,
    "rating": 5,
    "id": "tutor-4",
    "activeStudents": 16,
    "bio": "Сертификат CELTA, кембриджские методики, снятие языкового барьера.",
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "experienceYears": 11,
    "name": "Блинова Татьяна Викторовна"
  },
  {
    "telegram": "@tutor",
    "phone": "+7 (999) 000-00-00",
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    "education": "Куб Гу",
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "salesConversionRate": 80,
    "bio": "Главным считаю индивидуальный подход – могу выкроить курс под нужды каждого. Горжусь своими студентами, которые смогли влиться в сообщество во многих странах мира. Люблю работать со взрослыми, мой девиз: Learning can be fun! Конечно подготовка к ОГЭ и ЕГЭ уже не так весело, домашка обязательна, иногда нужен creative push, но могу гарантировать за год подъем на 40-50 баллов от входного уровня – научу что делать и как делать, что не делать и где ждать капканы)) Обожаю свою работу и своих студентов, со многими из которых мы стали друзьями!",
    "color": "indigo",
    "id": "tutor-1790414917592",
    "achievements": [],
    "name": "Лиходед Ольга Федоровна",
    "subjects": [
      "Английский язык",
      "ЕГЭ"
    ],
        "experienceYears": 30,
    "rating": 5,
    "activeStudents": 0,
    "shortName": "Ольга Лиходед"
  },
  {
    "bio": "В зависимости от запроса обговариваем с учениками путь работы. Для желающих заняться языком для себя я предлагаю уроки, которые я составляю сама, работаю по аутентике. Моя задача подстроиться под интересы студента и сделать урок полезным и интересным, так что темы для урока выбираем исходя из того, что интересно ученику.Для взрослых, изучающих язык для работы работаю по учебнику Market Leader.",
    "shortName": "Ларионова Екатерина",
    "id": "tutor-1790415174278",
    "achievements": [],
    "salesConversionRate": 80,
    "telegram": "@tutor",
        "rating": 4.95,
    "phone": "+7 (999) 000-00-00",
    "experienceYears": 6,
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    "education": "СПБГУ",
    "name": "Ларионова Екатерина",
    "activeStudents": 0,
    "color": "indigo",
    "subjects": [
      "Английский язык",
      "ОГЭ и ЕГЭ, IELTS",
      "8-11 класс"
    ]
  },
  {
    "subjects": [
      "Английский язык",
      "ОГЭ и ЕГЭ, IELTS",
      "взрослые",
      "1 - 7 класс"
    ],
    "salesConversionRate": 80,
    "color": "indigo",
    "experienceYears": 6,
    "shortName": "Шабрина Екатерина",
    "activeStudents": 0,
    "rating": 4.95,
    "bio": "Я стараюсь подстраивать объяснение под конкретного ученика: кому-то лучше заходят визуальные схемы и картинки, кому-то — игровые задания, кому-то необходимо разобрать правило максимально логично и пошагово. На занятиях использую визуальный материал, ассоциации, игровые элементы, примеры из интересов ребёнка и большое количество практики.\nБлагодаря обучению в области детской психологии и нейропсихологии я знаю особенности строения и развития мозга ребёнка, возрастные этапы формирования различных функций и особенности работы мозговых ритмов в разные периоды. Учитываю это при построении занятий и подборе методов обучения и запоминания в соответствии с возрастом и уровнем развития ребёнка.",
    "education": "",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "phone": "+7 (999) 000-00-00",
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    "name": "Шабрина Екатерина",
    "telegram": "@tutor",
    "achievements": [],
        "id": "tutor-1790415351670"
  },
  {
    "telegram": "@tutor",
    "name": "Фаззулина Альфия",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "avatar": "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
        "salesConversionRate": 80,
    "bio": "Объясняю материал просто и понятно, без лишней теории. На занятиях ученик активно участвует в процессе: я задаю наводящие вопросы и даю подсказки, чтобы он самостоятельно находил правильный ответ. Для меня важно не просто дать готовое решение, а научить ученика понимать и применять материал.\nЗа 8 лет работы помогла ученикам успешно подготовиться к разным экзаменам и преодолеть сложности в изучении языка. Среди результатов - максимальные баллы на ОГЭ и результаты 95+ на ЕГЭ.",
    "achievements": [],
    "experienceYears": 8,
    "color": "indigo",
    "education": "КФУ",
    "shortName": "Фаззулина Альфия",
    "rating": 4.95,
    "subjects": [
      "Английский язык",
      "ОГЭ, олимпиады",
      "7 - 9 класс"
    ],
    "phone": "+7 (999) 000-00-00",
    "id": "tutor-1790415645375",
    "activeStudents": 0
  },
  {
        "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    "color": "indigo",
    "bio": "С учениками младшей школы (1-4 класс) мы изучаем английский вместе с героями легенд и историй, ищем животных, спасаем город от монстров и путешествуем в разные миры, т.е. игровой подход: смотрим видео на английском, поем песни и играем в игры (jeopardy, bingo, tic-tac-toe etc.) \nС учениками постарше использую коммуникативный подход. Много говорим, отвечая на вопросы, описывая картинки, придумывая истории или обсуждая различные темы. Также много слушаем, работаем с видео, текстами, расширяем словарный запас и учимся применять новые знания в реальных коммуникативных ситуациях. \n Большинство учеников по английскому в школе выходят на оценку «отлично». Есть кейсы, где ребята учили со мной английский, а после окончания школы смогли учиться на английском в европейских университетах.",
    "education": "РГПУ им. А.И. Герцена",
    "name": "Иванова Владислава",
    "salesConversionRate": 80,
    "subjects": [
      "Английский язык",
      "1 - 9 класс - англ, + итальянский язык"
    ],
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "activeStudents": 0,
    "rating": 4.95,
    "experienceYears": 7,
    "id": "tutor-1790415895125",
    "achievements": [],
    "telegram": "@tutor",
    "phone": "+7 (999) 000-00-00",
    "shortName": "Иванова Владислава"
  },
  {
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "color": "indigo",
    "achievements": [],
    "name": "Силакова Ирина",
    "telegram": "@tutor",
    "rating": 4.95,
    "bio": "Преподаватель высшей категории с опытом подготовки к экзаменам.",
    "shortName": "Силакова Ирина",
    "subjects": [
      "Английский язык",
      "ОГЭ и ЕГЭ",
      "4 - 11 класс"
    ],
    "phone": "+7 (999) 000-00-00",
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    "education": "",
    "experienceYears": 5,
    "id": "tutor-1790416072218",
    "salesConversionRate": 80,
        "activeStudents": 0
  },
  {
    "education": "",
    "salesConversionRate": 80,
    "experienceYears": 20,
        "telegram": "@tutor",
    "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    "phone": "+7 (999) 000-00-00",
    "subjects": [
      "Английский язык",
      "ОГЭ и ЕГЭ, IELTS, 9 - 11 класс, взрослые"
    ],
    "rating": 4.95,
    "name": "Нелли",
    "bio": "Современный английский — это прежде всего язык общения и реальной жизни, а не набор правил для заучивания. Поэтому на занятиях мы много говорим, обсуждаем реальные ситуации и одновременно развиваем грамматику, произношение и словарный запас.\nЯ убеждена, что к каждому ученику нужен свой ключ. Поэтому подбираю методику с учётом цели, возраста, уровня, интересов и индивидуального темпа обучения.\nДля меня хороший урок — это тот, после которого знания постепенно превращаются в уверенность, свободу общения и ощутимый результат.",
    "shortName": "Нелли",
    "id": "tutor-1790416221532",
    "activeStudents": 0,
    "achievements": [],
    "color": "indigo",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ]
  },
  {
    "education": "НИУ ВШЭ",
    "subjects": [
      "Английский язык",
      "9-11 классы, взрослые",
      "ОГЭ и ЕГЭ, IELTS"
    ],
    "rating": 4.95,
    "phone": "+7 (999) 000-00-00",
        "experienceYears": 10,
    "bio": "Я всегда создаю уникальные для собственного опыта ученика задания, работаем исходя из любимого метода восприятия информации (визуалы, аудиалы, кинестетики), даю много примеров как и для академического английского, так и для разговорного (мои ученики знают, как будут общаться с другом по переписке из Британии и как – с консулом или начальником) \nНа занятия приглашаю носителей из англоязычных стран для практики устной речи.",
    "activeStudents": 0,
    "achievements": [],
    "color": "indigo",
    "name": "Федорова Алла",
    "shortName": "Федорова Алла",
    "telegram": "@tutor",
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "avatar": "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    "salesConversionRate": 80,
    "id": "tutor-1790416520693"
  },
  {
    "activeStudents": 0,
    "bio": "Преподаватель высшей категории с опытом подготовки к экзаменам.",
    "phone": "+7 (999) 000-00-00",
    "telegram": "@tutor",
    "id": "tutor-1790416675377",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "shortName": "Родионова Юлия",
    "experienceYears": 6,
    "salesConversionRate": 80,
    "rating": 4.95,
    "color": "indigo",
    "avatar": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    "name": "Родионова Юлия",
    "achievements": [],
    "subjects": [
      "Английский язык",
      "взрослые, IELTS"
    ],
        "education": ""
  },
  {
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "id": "tutor-1790416892833",
    "education": "",
    "experienceYears": 6,
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
        "color": "indigo",
    "salesConversionRate": 80,
    "subjects": [
      "Английский язык",
      "1-10 класс, не берет ОГЭ/ЕГЭ"
    ],
    "activeStudents": 0,
    "shortName": "Андрюшечкина Татьяна",
    "rating": 4.95,
    "telegram": "@tutor",
    "achievements": [],
    "bio": "",
    "phone": "+7 (999) 000-00-00",
    "name": "Андрюшечкина Татьяна Сергеевна"
  },
  {
    "activeStudents": 0,
    "experienceYears": 9,
    "education": "Бурятский государственный университет",
    "telegram": "@tutor",
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    "color": "indigo",
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "achievements": [],
    "shortName": "Суханов Булат",
    "salesConversionRate": 80,
    "rating": 4.95,
    "id": "tutor-1790417138498",
    "bio": "Акцент ставлю на разговорной практике и аудировании - это естественно для людей, родной язык мы изучали также.\nИспользуем фильмы, игры, книги, сериалы, подкасты - все, что интересно ученику и позволяет повысить интерес.",
    "phone": "+7 (999) 000-00-00",
    "name": "Суханов Булат Геннадьевич",
    "subjects": [
      "Английский язык",
      "1-11 класс, взрослые,ЕГЭ, ОГЭ, FCE, TOEFL, HSK",
      "Китайский язык"
    ],
      },
  {
    "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    "id": "tutor-1790417611671",
    "telegram": "@tutor",
        "bio": "Работаю с разными уровнями, стремлюсь к каждому ученику найти индивидуальный подход: кому-то интереснее выполнять интерактивные упражнения в игровой форме, кто-то любит поговорить о своих хобби, встречаются даже такие, кто предпочитает выполнять письменные задания.\nМоя главная задача - убрать у учеников страх перед языком, донести до них, что делать ошибки - это нормально, главное учиться на них и двигаться вперед",
    "phone": "+7 (999) 000-00-00",
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "education": "Новосибирский государственный педагогический университет",
    "experienceYears": 6,
    "activeStudents": 0,
    "achievements": [],
    "salesConversionRate": 80,
    "color": "indigo",
    "rating": 4.95,
    "shortName": "Лукьянова Светлана",
    "name": "Лукьянова Светлана",
    "subjects": [
      "Английский язык",
      "1-10 класс, не берет ОГЭ/ЕГЭ, но берет ВПР"
    ]
  },
  {
        "shortName": "Агабекян Милана",
    "salesConversionRate": 80,
    "name": "Агабекян Милана Ихтиадровна",
    "bio": "Мои занятия начинаются с диагностики - задача ученика показать свои коммуникативные навыки, умение прочитать и пересказать текст, описать «странную» картинку, а уже после такого анализа , я четко определяю уровень подопечного ☺️ чтобы мой ученик развивал свой английский и не загонял себя в рамки экзамена, я делаю уроки разнообразными - чередую форматные занятия с разбором статеек на разные тематики, превращаю экзамен в более глубокую работу над каждым заданием.\n Более 15 моих учеников сдали ОГЭ на максимум 👐🏻 это те люди, которые четко следовали моим рекомендациям! Мы также вместе успешно готовимся к муверсам, флаерсам и так далее.",
    "rating": 4.95,
    "telegram": "@tutor",
    "phone": "+7 (999) 000-00-00",
    "activeStudents": 0,
    "experienceYears": 6,
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "education": "",
    "color": "indigo",
    "id": "tutor-1790417831952",
    "subjects": [
      "Английский язык",
      "1-9 класс ОГЭ"
    ],
    "achievements": [],
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80"
  },
  {
    "bio": "Почему должны выбрать именно меня? Я не заставляю зубрить правила. Я объясняю в привычной для ребенка тематике :\n— Создаю тематическое оформление урока с помощью картинок, стикеров и мотивирующих фраз;  — Использую любимые игры и сериалы учеников (Minecraft, Brawl Stars, Гарри Поттер и т.д.); — Грамматику показываю через тематические таблички (мемы и картинки), чтобы правила быстрее запомнились; — Для меня важно, чтобы ученик не боялся ошибаться. Моя цель — не «выучить», а «понять и начать использовать». Работаю в Teams и Zoom, все материалы остаются у ученика навсегда.",
    "id": "tutor-1790417983411",
    "phone": "+7 (999) 000-00-00",
    "avatar": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "name": "Нечай Анастасия Дмитриевна",
    "shortName": "Нечай Анастасия",
    "subjects": [
      "Английский язык",
      "5-9 класс",
      "Русский язык"
    ],
    "salesConversionRate": 80,
    "telegram": "@tutor",
    "experienceYears": 6,
    "color": "indigo",
    "achievements": [],
        "education": "Санкт-Петербургский государственный университет",
    "activeStudents": 0,
    "rating": 4.95
  },
  {
    "salesConversionRate": 80,
    "phone": "+7 (999) 000-00-00",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    "telegram": "@tutor",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
        "activeStudents": 0,
    "bio": "",
    "education": "",
    "color": "indigo",
    "experienceYears": 6,
    "id": "tutor-1790418265359",
    "shortName": "Патрик",
    "achievements": [],
    "name": "Патрик",
    "rating": 4.95,
    "subjects": [
      "Английский язык"
    ]
  },
  {
    "experienceYears": 7,
        "color": "indigo",
    "salesConversionRate": 80,
    "education": "",
    "telegram": "@tutor",
    "achievements": [],
    "rating": 4.95,
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "name": "Макс",
    "activeStudents": 0,
    "subjects": [
      "Английский язык",
      "1 - 11 класс, взрослые"
    ],
    "bio": "",
    "phone": "+7 (999) 000-00-00",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    "id": "tutor-1790418329554",
    "shortName": "Макс"
  },
  {
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "subjects": [
      "Английский язык"
    ],
    "rating": 4.95,
    "activeStudents": 0,
    "shortName": "Джозеф",
    "phone": "+7 (999) 000-00-00",
    "name": "Джозеф",
    "achievements": [],
    "education": "",
        "experienceYears": 6,
    "color": "indigo",
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    "telegram": "@tutor",
    "salesConversionRate": 80,
    "bio": "",
    "id": "tutor-1790418412184"
  },
  {
    "avatar": "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    "activeStudents": 0,
    "name": "Федотова Марина Владимировна",
    "id": "tutor-1790418594000",
        "experienceYears": 30,
    "bio": "В образовательном процессе уделяю большое внимание произношению, коммуникативной направленности и культурно - страноведческим аспектам с использованием книг, песен и других аутентичных материалов для повышения мотивации учеников.",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "phone": "+7 (999) 000-00-00",
    "education": "ТГПУ им.Л.Н.Толстого",
    "subjects": [
      "Школьники, взрослые. Языковые тесты для эмиграции в Канаду TEF/TCF, для Франции: DELF/DALF",
      "Английский язык",
      "Фанцуский язык"
    ],
    "telegram": "@tutor",
    "rating": 4.95,
    "shortName": "Марина Владимировна",
    "salesConversionRate": 80,
    "color": "indigo",
    "achievements": []
  },
  {
    "telegram": "@tutor",
    "name": "Кузнецов Андрей Владимирович",
    "salesConversionRate": 80,
    "bio": "",
    "phone": "+7 (999) 000-00-00",
        "achievements": [],
    "shortName": "Андрей Владимирович",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    "rating": 4.95,
    "color": "indigo",
    "experienceYears": 6,
    "subjects": [
      "Француский язык"
    ],
    "id": "tutor-1790418720859",
    "activeStudents": 0,
    "education": ""
  },
  {
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
        "color": "indigo",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    "achievements": [],
    "subjects": [
      "Китайский язык",
      "1-11 класс, взрослые"
    ],
    "name": "Романенко Александр",
    "bio": "Мой подход: мы не просто зубрим иероглифы, а сразу применяем их в речи. Я уделяю особое внимание фонетике и постановке тонов, а также этимологии иероглифов — так ученик понимает логику языка, а не просто заучивает символы. Поскольку я живу в Китае, я делюсь актуальным сленгом и страноведческими реалиями, которые не найдёшь в учебниках. Я гарантирую, что на моих уроках не будет скучно.",
    "education": "Московский городской педагогический университет по специальности «Лингвистика» (бакалавр)",
    "phone": "+7 (999) 000-00-00",
    "shortName": "Романенко Александр",
    "id": "tutor-1790419078986",
    "rating": 4.95,
    "telegram": "@tutor",
    "experienceYears": 16,
    "activeStudents": 0,
    "salesConversionRate": 80
  },
  {
    "color": "indigo",
    "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    "subjects": [
      "Немецкий язык",
      "3-11 классы"
    ],
    "name": "Волкова Анна Витальевна",
    "experienceYears": 6,
    "shortName": "Волкова Анна",
    "id": "tutor-1790419164612",
    "bio": "",
    "salesConversionRate": 80,
    "phone": "+7 (999) 000-00-00",
    "activeStudents": 0,
    "achievements": [],
        "rating": 4.95,
    "telegram": "@tutor",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "education": ""
  },
  {
    "rating": 4.95,
    "name": "Диана Сергеевна Рубцова",
    "education": "Чувашский государственный педагогический университет имени И. И. Яковлева",
    "bio": "Зубрёжка правил из учебника - не мой формат: я объясняю именно логику языка. \nМне важна психологическая атмосфера, поэтому на уроках я создаю полное ощущение безопасности. Если ребёнок не понимает тему со 2-го, 3-го или 10-го раза, в этом нет ничего страшного. Мы спокойно разберём один и тот же материал столько раз, сколько понадобится.\nНа занятиях мы всегда работаем с наглядными таблицами, авторскими карточками и схемами. А если тема даётся тяжело, разбираем её на жизненных школьных примерах или сюжетных линиях из любимых игр ученика.",
    "salesConversionRate": 80,
        "phone": "+7 (999) 000-00-00",
    "telegram": "@tutor",
    "id": "tutor-1790419420798",
    "shortName": "Диана  Рубцова",
    "subjects": [
      "Русский язык",
      "5-8 класс"
    ],
    "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    "achievements": [],
    "activeStudents": 0,
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "experienceYears": 9,
    "color": "indigo"
  },
  {
        "name": "Сафаргалина Арина Владимировна",
    "bio": "За время работы я помогла более 100 школьникам повысить успеваемость: у большинства с «2», «3» поднялись до «4» и «5». Мои ученики сдали ОГЭ на «4» и «5», а каждый второй выпускнико получил 80+ баллов на ЕГЭ. Также есть опыт подготовки к ВПР и итоговому сочинению. Один из учеников за учебный год улучшил результат с 35 до 91 балла на пробном ЕГЭ.",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "shortName": "Сафаргалина Арина",
    "subjects": [
      "Русский язык",
      "5-11 классы, ОГЭ и ЕГЭ"
    ],
    "rating": 4.95,
    "color": "indigo",
    "activeStudents": 0,
    "education": "Удмуртский государственный университет по направлению «Прикладная филология» с углублённым изучением методики преподавания русского языка",
    "id": "tutor-1790419749103",
    "experienceYears": 5,
    "phone": "+7 (999) 000-00-00",
    "salesConversionRate": 80,
    "achievements": [],
    "telegram": "@tutor",
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80"
  },
  {
    "name": "Абдулгужина Оксана Михайловна",
    "achievements": [],
    "education": "",
    "subjects": [
      "Русский язык"
    ],
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    "salesConversionRate": 80,
    "activeStudents": 0,
    "phone": "+7 (999) 000-00-00",
    "rating": 4.95,
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "telegram": "@tutor",
    "experienceYears": 6,
        "bio": "",
    "id": "tutor-1790419959203",
    "color": "indigo",
    "shortName": "Абдулгужина Оксана"
  },
  {
    "phone": "+7 (999) 000-00-00",
    "achievements": [],
    "activeStudents": 0,
    "shortName": "Лотова Милена",
    "rating": 4.95,
    "subjects": [
      "Русский язык",
      "5-11 классы ОГЭ и ЕГЭ"
    ],
    "bio": "Я стараюсь не просто объяснить тему, а сделать так, чтобы ученик действительно понял, почему правило работает именно так. Не использую один шаблон для всех — подстраиваю объяснение под возраст, уровень знаний и особенности конкретного ребёнка.\nС младшими учениками часто использую ассоциации. Со школьниками постарше больше работаем через практику: разбираем ошибки, учимся находить закономерности и постепенно усложняем задания.\nМоя сильная сторона — это умение внушить ребенку , что он сможет! Я стараюсь создать атмосферу, в которой ребёнок не боится отвечать и пробовать. Считаю важным не только подтянуть оценки, но и сформировать у ученика уверенность в своих знаниях. Ну слишком самоуверенных ,наоборот, приходится приземлять.",
    "experienceYears": 6,
    "education": "ДАГГАУ ЭКОНОМИЧЕСКИЙ",
    "salesConversionRate": 80,
    "color": "indigo",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "telegram": "@tutor",
        "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    "id": "tutor-1790420715731",
    "name": "Лотова Милена"
  },
  {
    "achievements": [],
    "experienceYears": 6,
    "color": "indigo",
    "telegram": "@tutor",
    "rating": 4.95,
    "education": "Окончила Волгоградский государственный университет по направлению «Экология и природопользование».",
    "salesConversionRate": 80,
    "name": "Варвара Александровна",
    "bio": "На занятиях я опираюсь на интерес ученика. Материал подаю наглядно: схемы, картинки, примеры из жизни. Считаю важным не оценивать работы по шаблону и давать ученику время подумать, а не требовать мгновенного ответа.",
    "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    "activeStudents": 0,
    "subjects": [
      "Русский язык",
      "5-11 классы, ОГЭ и ЕГЭ"
    ],
    "phone": "+7 (999) 000-00-00",
        "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "shortName": "Варвара Александровна",
    "id": "tutor-1790421984925"
  },
  {
    "rating": 4.95,
    "subjects": [
      "Русский язык"
    ],
    "shortName": "Наталья Ушакова",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "salesConversionRate": 80,
    "targetGoals": [
      "ege",
      "oge",
      "olympiad",
      "grades"
    ],
    "phone": "+7 (999) 000-00-00",
    "targetGrades": [
      "1-4",
      "5-8",
      "9",
      "10",
      "11"
    ],
    "achievements": [],
    "experienceYears": 6,
    "name": "Наталья Александровна Ушакова",
    "id": "tutor-1790422040136",
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    "telegram": "@tutor",
    "bio": "",
    "activeStudents": 0,
    "color": "indigo"
  },
  {
    "activeStudents": 0,
    "rating": 4.95,
    "bio": "",
    "education": "",
    "subjects": [
      "Русский язык"
    ],
    "color": "indigo",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "salesConversionRate": 80,
    "id": "tutor-1790422084852",
    "experienceYears": 6,
    "telegram": "@tutor",
        "avatar": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    "phone": "+7 (999) 000-00-00",
    "achievements": [],
    "name": "Елизавета Владимировна",
    "shortName": "Елизавета Владимировна"
  },
  {
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "shortName": "Ольга Игоревна",
    "experienceYears": 6,
    "id": "tutor-1790422304433",
    "phone": "+7 (999) 000-00-00",
    "activeStudents": 0,
    "subjects": [
      "Русский язык",
      "Литература"
    ],
    "rating": 4.95,
    "telegram": "@tutor",
    "name": "Ольга Игоревна",
    "education": "",
    "salesConversionRate": 80,
    "color": "indigo",
    "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    "bio": "",
        "achievements": []
  },
  {
    "experienceYears": 6,
    "subjects": [
      "Русский язык"
    ],
    "bio": "",
    "education": "",
    "avatar": "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    "activeStudents": 0,
    "phone": "+7 (999) 000-00-00",
    "salesConversionRate": 80,
    "rating": 4.95,
        "id": "tutor-1790422346946",
    "color": "indigo",
    "name": "Яна",
    "achievements": [],
    "telegram": "@tutor",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "shortName": "Яна"
  },
  {
    "rating": 4.95,
    "phone": "+7 (999) 000-00-00",
    "activeStudents": 0,
    "subjects": [
      "Математика (профиль)",
      "Математика (база)",
      "8-11 класс"
    ],
    "name": "Екатерина Романовна Чуркина",
    "shortName": "Екатерина Чуркина",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "telegram": "@tutor",
    "experienceYears": 6,
    "salesConversionRate": 80,
    "achievements": [],
    "avatar": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    "education": "",
    "color": "indigo",
        "bio": "",
    "id": "tutor-1790422911767"
  },
  {
    "phone": "+7 (999) 000-00-00",
    "shortName": "Екатерина Ухабина",
    "salesConversionRate": 80,
    "subjects": [
      "Математика (база)",
      "5-9 класс ОГЭ"
    ],
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    "experienceYears": 6,
    "id": "tutor-1790423035632",
    "education": "ЮУрГГПУ",
    "telegram": "@tutor",
    "color": "indigo",
    "achievements": [],
    "rating": 4.95,
    "bio": "Использую классическую методику: учебник, тетрадь, последовательная отработка каждой темы. Никаких игр и развлечений — только системный подход.",
        "name": "Екатерина Ухабина",
    "activeStudents": 0
  },
  {
    "education": "АНО «НИУДПО им. К. Д. Ушинского»",
    "color": "indigo",
    "name": "Кучерова Софья",
    "rating": 4.95,
    "experienceYears": 6,
    "telegram": "@tutor",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "id": "tutor-1790423234558",
    "salesConversionRate": 80,
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    "shortName": "Кучерова Софья",
        "subjects": [
      "Математика (профиль)",
      "Математика (база)"
    ],
    "bio": "В основе занятий — индивидуальный подход. Я стараюсь понять, как именно ученику проще воспринимать информацию, что ему интересно и где возникают трудности.\nОбъясняю материал простым языком, через понятные примеры и ассоциации, иногда связывая тему с увлечениями ученика. На занятиях важна спокойная и дружелюбная атмосфера, в которой можно задавать вопросы, ошибаться, пробовать снова и постепенно приходить к уверенному пониманию предмета.\nДля меня важно не просто научить решать конкретный тип задач, а помочь ученику понять логику и научиться самостоятельно применять знания",
    "activeStudents": 0,
    "phone": "+7 (999) 000-00-00",
    "achievements": []
  },
  {
    "education": "",
    "subjects": [
      "Математика (профиль)",
      "Математика (база)"
    ],
    "phone": "+7 (999) 000-00-00",
    "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    "id": "tutor-1790423404277",
    "experienceYears": 6,
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "salesConversionRate": 80,
    "activeStudents": 0,
    "bio": "",
    "color": "indigo",
    "shortName": "Милана",
    "name": "Милана",
    "telegram": "@tutor",
        "achievements": [],
    "rating": 4.95
  },
  {
        "name": "Марина Кулешова",
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "avatar": "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150&auto=format&fit=crop&q=80",
    "id": "tutor-1790423551364",
    "activeStudents": 0,
    "experienceYears": 2,
    "education": "КубГТУ на направлении «Программная инженерия»",
    "subjects": [
      "Математика (база)",
      "7-11 клас  ОГЭ и ЕГЭ(база)"
    ],
    "phone": "+7 (999) 000-00-00",
    "telegram": "@tutor",
    "bio": "На занятиях я делаю упор на максимальную наглядность и психологический комфорт. Я активно использую современные интерактивные доски (например, Яндекс доска, квизы), наглядные презентации и подбадривающие визуальные материалы.\nНаглядность помогает перевести сухие, абстрактные формулы в понятные образы и схемы.\nПсихологический комфорт снимает страх ошибки — ученики перестают бояться математики, не стесняются переспрашивать и начинают по-настоящему вникать в предмет.",
    "achievements": [],
    "salesConversionRate": 80,
    "rating": 4.95,
    "shortName": "Марина Кулешова",
    "color": "indigo"
  },
  {
    "shortName": "Наталья Игоревна",
        "name": "Наталья Игоревна",
    "rating": 4.95,
    "telegram": "@tutor",
    "id": "tutor-1790423656933",
    "color": "indigo",
    "salesConversionRate": 80,
    "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    "subjects": [
      "Математика (база)"
    ],
    "achievements": [],
    "activeStudents": 0,
    "education": "",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "phone": "+7 (999) 000-00-00",
    "bio": "",
    "experienceYears": 6
  },
  {
    "shortName": "Кирсанов Кирилл",
    "bio": "",
    "rating": 4.95,
    "telegram": "@tutor",
    "color": "indigo",
    "achievements": [],
    "activeStudents": 0,
    "name": "Кирсанов Кирилл Александрович",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "experienceYears": 6,
    "id": "tutor-1790423953864",
        "education": "",
    "phone": "+7 (999) 000-00-00",
    "salesConversionRate": 80,
    "subjects": [
      "Химия"
    ],
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80"
  },
  {
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "subjects": [
      "Биология",
      "6-11 класс ОГЭ и ЕГЭ, олимпиады"
    ],
    "avatar": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    "experienceYears": 6,
    "shortName": "Фастова Анна",
    "salesConversionRate": 80,
        "phone": "+7 (999) 000-00-00",
    "bio": "Я использую мягкий подход, без давления. Хочу чтобы ребенку было интересно, привожу примеры из жизни, а также примеры из опыта работы в лаборатории",
    "id": "tutor-1790424082603",
    "activeStudents": 0,
    "name": "Фастова Анна Сергеевна",
    "education": "Южный федеральный университет",
    "achievements": [],
    "telegram": "@tutor",
    "rating": 4.95,
    "color": "indigo"
  },
  {
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "subjects": [
      "Биология"
    ],
    "salesConversionRate": 80,
        "rating": 4.95,
    "bio": "",
    "education": "",
    "phone": "+7 (999) 000-00-00",
    "achievements": [],
    "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    "id": "tutor-1790424164388",
    "experienceYears": 6,
    "name": "Егорова Анна Александровна",
    "telegram": "@tutor",
    "color": "indigo",
    "shortName": "Егорова Анна",
    "activeStudents": 0
  },
  {
    "rating": 4.95,
    "experienceYears": 6,
    "activeStudents": 0,
    "name": "Быковская Екатерина",
    "education": "",
    "subjects": [
      "Биология",
      "6-9 класс ОГЭ"
    ],
    "salesConversionRate": 80,
    "phone": "+7 (999) 000-00-00",
    "id": "tutor-1790424217907",
    "bio": "",
    "shortName": "Быковская Екатерина",
    "achievements": [],
    "telegram": "@tutor",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
        "avatar": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    "color": "indigo"
  },
  {
    "education": "",
    "subjects": [
      "Биология"
    ],
    "activeStudents": 0,
    "phone": "+7 (999) 000-00-00",
    "rating": 4.95,
    "salesConversionRate": 80,
    "name": "Дмитревская Павла Данииловна",
    "achievements": [],
        "experienceYears": 6,
    "color": "indigo",
    "shortName": "Дмитревская Павла",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "id": "tutor-1790424272817",
    "telegram": "@tutor",
    "bio": "",
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80"
  },
  {
    "activeStudents": 0,
    "achievements": [],
    "phone": "+7 (999) 000-00-00",
    "telegram": "@tutor",
        "id": "tutor-1790424332566",
    "experienceYears": 6,
    "salesConversionRate": 80,
    "education": "",
    "rating": 4.95,
    "bio": "",
    "color": "indigo",
    "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    "name": "Гришанова Дарья Юрьевна",
    "shortName": "Гришанова Дарья",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "subjects": [
      "История"
    ]
  },
  {
    "shortName": "Сусликова Ирина",
    "name": "Сусликова Ирина Александровна",
    "achievements": [],
    "id": "tutor-1790424481388",
    "telegram": "@tutor",
    "color": "indigo",
        "salesConversionRate": 80,
    "avatar": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    "bio": "Мои методы обучения носят исключительно индивидуальный характер: игровые методики, визуальный материал, карточки, викторины. Я сначала изучаю индивидуальные особенности ученика и далее в соответствии с этим разрабатываю программу. Если ученику близки фильмы, игры, современные ситуации или определённые увлечения, могу использовать знакомые ему примеры, чтобы объяснить сложную тему. Я стараюсь объяснять материал простым языком и обязательно связываю новую информацию с тем, что ученик уже знает.\nЗа время преподавания я подготовила много учеников по истории и обществознанию. Среди результатов моих учеников —рост баллов с 45–50 до 75+ баллов, а также результаты ЕГЭ 80+. Особенно ценю не только высокие итоговые баллы, но и случаи, когда ученик приходит практически без базы, боится предмета или уверен, что «история ему вообще не даётся», а спустя несколько месяцев уже самостоятельно разбирает задания и может объяснить причинно-следственные связи.",
    "rating": 4.95,
    "education": "Российский государственный социальный университет по специальности \"Всеобщая история\"",
    "activeStudents": 0,
    "phone": "+7 (999) 000-00-00",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "subjects": [
      "История",
      "5-11 класс ОГЭ и ЕГЭ",
      "Обществознание"
    ],
    "experienceYears": 6
  },
  {
    "experienceYears": 6,
    "telegram": "@tutor",
    "salesConversionRate": 80,
    "name": "Гадакчян Аристакес Левонович",
    "activeStudents": 0,
    "education": "",
    "phone": "+7 (999) 000-00-00",
        "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    "shortName": "Гадакчян Аристакес",
    "bio": "",
    "rating": 4.95,
    "color": "indigo",
    "achievements": [],
    "id": "tutor-1790429255976",
    "subjects": [
      "Информатика (Python)",
      "7-10 класс ОГЭ"
    ],
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ]
  },
  {
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "color": "indigo",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    "subjects": [
      "Информатика (Python)",
      "3-11 класс ОГЭ/ЕГЭ"
    ],
    "education": "Симферопольский политехнический колледж",
    "id": "tutor-1790429428974",
    "bio": "Наверное радость ребёнка, когда он сделал что то сам и у него получилось, пусть и не с первой попытки. \nПомнится, дети собрали машину на базе Ардуино, используя в качестве шасси коробку из под обуви и палочки для суши",
    "experienceYears": 6,
    "achievements": [],
    "phone": "+7 (999) 000-00-00",
    "shortName": "Оболенский Даниил",
    "activeStudents": 0,
        "telegram": "@tutor",
    "salesConversionRate": 80,
    "name": "Оболенский Даниил Алексеевич",
    "rating": 4.95
  },
  {
    "shortName": "Моисеева Валентина",
    "telegram": "@tutor",
    "activeStudents": 0,
        "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    "phone": "+7 (999) 000-00-00",
    "experienceYears": 10,
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "achievements": [],
    "rating": 4.95,
    "education": "Ставропольский государственный педагогический институт",
    "bio": "В своих онлайн-занятиях по ментальной арифметике я использую специализированные профессиональные платформы. У каждого моего ученика есть свой личный кабинет, где мы в режиме реального времени решаем примеры. Это удерживает азарт и интерес ребенка на протяжении всего урока.Прогрессивные онлайн-платформы: Я активно интегрирую в уроки передовые образовательные сервисы. Мы используем платформу LogicLike для решения нестандартных логических задач по математике, а также специализированные программы-тренажеры по русскому языку. Нейрогимнастика и тренировка фокуса: Дистанционный урок требует особой динамики. Прямо во время занятий я использую нейрогимнастику (кинезиологические упражнения для синхронизации полушарий) и интерактивные задания на развитие зрительной памяти и концентрации внимания.",
    "subjects": [
      "Ментальная арифметика",
      "1-4 класс, в основном ментальная арифметика, но берет русский и математику 1-4 класс"
    ],
    "id": "tutor-1790429586676",
    "color": "indigo",
    "name": "Моисеева Валентина Николаевна",
    "salesConversionRate": 80
  },
  {
    "salesConversionRate": 80,
    "shortName": "Дмитрий Иванович",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "activeStudents": 0,
    "color": "indigo",
    "bio": "",
    "experienceYears": 6,
    "rating": 4.95,
    "subjects": [
      "Шахматы",
      "все возраста"
    ],
    "name": "Зубов Дмитрий Иванович",
    "telegram": "@tutor",
    "phone": "+7 (999) 000-00-00",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    "education": "",
        "achievements": [],
    "id": "tutor-1790429822570"
  },
  {
    "bio": "Если говорить о нейрогимнастике, то я подготавливаю различные интересные интерактивные задания, которые направлены на улучшение успеваемости и развитие речи, логики, памяти, пространственного мышления, саморегуляции.",
        "achievements": [],
    "activeStudents": 0,
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "education": "Южный федеральный университет, 2021. «Педагогическое образование с двумя профилями подготовки»,  квалификация: учитель русского языка и литературы.",
    "phone": "+7 (999) 000-00-00",
    "rating": 4.95,
    "telegram": "@tutor",
    "experienceYears": 6,
    "id": "tutor-1790429995803",
    "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    "salesConversionRate": 80,
    "subjects": [
      "Психолог логопед"
    ],
    "name": "Городничева Виктория (Педагог-дефектолог, медицинский логопед)",
    "color": "indigo",
    "shortName": "Городничева Виктория"
  },
  {
    "activeStudents": 0,
    "phone": "+7 (999) 000-00-00",
    "experienceYears": 6,
        "telegram": "@tutor",
    "education": "",
    "rating": 4.95,
    "color": "indigo",
    "subjects": [
      "Психолог"
    ],
    "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    "achievements": [],
    "id": "tutor-1790430072818",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "bio": "",
    "salesConversionRate": 80,
    "name": "Галухин Алина (психолог)",
    "shortName": "Галухин Алина"
  },
  {
        "telegram": "@tutor",
    "id": "tutor-1790677202257",
    "name": "Медведева Александра Максимовна",
    "shortName": "Медведева Александра",
    "rating": 4.95,
    "activeStudents": 0,
    "phone": "+7 (999) 000-00-00",
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "education": "Межрегиональный институт развития",
    "avatar": "https://chatgpt.com/backend-api/estuary/content?id=file_000000001d6c81f48ef4beace9fe3b59&fn=d889886d-2223-4e43-969f-4599922f784c.jpeg&cd=attachment&ts=497432&p=fs&cid=1&sig=fca1e984c0762c7fd8f571819c1254e18454c19214890bf40348285af433a709&v=0",
    "experienceYears": 8,
    "salesConversionRate": 80,
    "achievements": [
      "Победитель регионального конкурса дополнительных общеразвивающих программ"
    ],
    "bio": "Преподаватель высшей категории с опытом подготовки к экзаменам.",
    "subjects": [
      "Английский язык",
      "ЕГЭ",
      "ОГЭ",
      "IELTS"
    ],
    "color": "indigo"
  },
  {
    "name": "Анна Стадник",
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "bio": "",
    "education": "СПбПУ",
    "subjects": [
      "Математика (база)",
      "Математика (профиль)",
      "Начальная школа"
    ],
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    "salesConversionRate": 80,
    "phone": "+7 (999) 000-00-00",
    "id": "tutor-1790751396369",
    "rating": 4.99,
    "telegram": "@tutor",
        "experienceYears": 6,
    "achievements": [],
    "activeStudents": 0,
    "shortName": "Анна Стадник",
    "color": "indigo"
  },
  {
    "subjects": [
      "Математика (профиль)",
      "Математика (база)"
    ],
    "id": "tutor-1790771424183",
    "color": "indigo",
    "education": "",
    "name": "Марина Анатольевна",
    "experienceYears": 6,
    "achievements": [],
    "activeStudents": 0,
    "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    "shortName": "Марина Анатольевна",
    "bio": "",
    "salesConversionRate": 80,
    "phone": "+7 (999) 000-00-00",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "rating": 4.95,
    "telegram": "@tutor",
      },
  {
    "id": "tutor-1790771768608",
    "achievements": [],
    "subjects": [
      "Химия"
    ],
    "experienceYears": 6,
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    "color": "indigo",
    "shortName": "Кирилл Иванович",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "salesConversionRate": 80,
        "activeStudents": 0,
    "rating": 4.95,
    "phone": "+7 (999) 000-00-00",
    "bio": "",
    "education": "",
    "name": "Кирилл Иванович",
    "telegram": "@tutor"
  },
  {
    "subjects": [
      "Математика (профиль)",
      "Математика (база)",
      "Экономика"
    ],
    "activeStudents": 0,
    "achievements": [],
    "id": "tutor-1790774753420",
    "rating": 4.95,
    "color": "indigo",
    "shortName": "Дмитрий",
        "salesConversionRate": 80,
    "education": "МГУ им. Ломоносова, экономический и педагогический факультеты, кандидат наук",
    "name": "Дмитрий",
    "phone": "+7 (999) 000-00-00",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "experienceYears": 6,
    "bio": "Глубокое погружение в логику предмета. Объясняю с разных сторон, много практики\n ОГЭ - 90% повысили свою текущую оценку на 1 балл и сдали на 4-5, ЕГЭ - 30% 80+, средний балл - 75\n Ученик был настолько трудолюбив, что придя в начале учебного года с \"3\", в итоге сдал ОГЭ почти на максимум",
    "telegram": "@tutor",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80"
  },
  {
    "subjects": [
      "Математика (профиль)",
      "Математика (база)"
    ],
    "rating": 4.95,
    "experienceYears": 6,
        "id": "tutor-1790782140117",
    "color": "indigo",
    "salesConversionRate": 80,
    "name": "София",
    "shortName": "София",
    "achievements": [],
    "activeStudents": 0,
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "education": "ННГУ им. Н.И. Лобачевского, специальность: Математика,",
    "avatar": "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    "phone": "+7 (999) 000-00-00",
    "bio": "Мой главный принцип — учить думать самостоятельно. Я никогда не даю готовых решений: шаг за шагом задаю наводящие вопросы, чтобы ученик сам дошел до правильного ответа и почувствовал уверенность в своих силах. С учениками мы легко находим общий язык, так как разница в возрасте небольшая, благодаря чему уроки проходят без стресса, стеснения и «боязни совершить ошибку».",
    "telegram": "@tutor"
  },
  {
    "shortName": "Руслан Тахирович",
    "rating": 5,
        "phone": "+7 (999) 000-00-00",
    "activeStudents": 0,
    "subjects": [
      "Математика (профиль)",
      "Математика (база)",
      "Информатика (Python)"
    ],
    "id": "tutor-1790864015054",
    "name": "Еремеев Руслан Тахирович",
    "achievements": [
      "Подготовка учеников на 90+"
    ],
    "salesConversionRate": 80,
    "telegram": "@tutor",
    "bio": "Преподаватель высшей категории с опытом подготовки к экзаменам.",
    "education": "ТГУ",
    "color": "indigo",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "experienceYears": 4,
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "tutor-1791187311729",
    "telegram": "@tutor",
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "education": "",
    "bio": "",
    "phone": "+7 (999) 000-00-00",
    "rating": 4.95,
    "experienceYears": 6,
    "activeStudents": 0,
    "avatar": "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150&auto=format&fit=crop&q=80",
    "achievements": [],
        "shortName": "Таисия Филатова",
    "color": "indigo",
    "subjects": [
      "Английский язык"
    ],
    "name": "Таисия Филатова",
    "salesConversionRate": 80
  },
  {
    "phone": "+7 (999) 000-00-00",
    "education": "",
    "subjects": [
      "Английский язык"
    ],
    "salesConversionRate": 80,
    "achievements": [],
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "avatar": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    "bio": "",
    "color": "indigo",
    "shortName": "Манасян Анаит",
    "rating": 5,
    "activeStudents": 0,
        "id": "tutor-1790418070286",
    "telegram": "@tutor",
    "name": "Манасян Анаит",
    "experienceYears": 4
  },
  {
    "experienceYears": 6,
    "bio": "",
    "rating": 4.95,
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "activeStudents": 0,
    "id": "tutor-1790418757666",
    "subjects": [
      "Французскаий язык"
    ],
    "name": "Манасян Анаит",
    "salesConversionRate": 80,
        "color": "indigo",
    "shortName": "Манасян Анаит",
    "achievements": [],
    "avatar": "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    "education": "",
    "phone": "+7 (999) 000-00-00",
    "telegram": "@tutor"
  },
  {
    "phone": "+7 (999) 000-00-00",
    "subjects": [
      "Обществознание"
    ],
    "shortName": "Дарья Юрьевна",
    "experienceYears": 6,
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
    "name": "Гришанова Дарья Юрьевна",
    "avatar": "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150&auto=format&fit=crop&q=80",
    "education": "",
    "color": "indigo",
    "rating": 4.95,
    "activeStudents": 0,
    "achievements": [],
    "id": "tutor-1790429018565",
        "salesConversionRate": 80,
    "bio": "",
    "telegram": "@tutor"
  },
  {
    "avatar": "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    "subjects": [
      "География"
    ],
    "availableDays": [
      1,
      2,
      3,
      4,
      5
    ],
        "id": "tutor-1790429139499",
    "name": "Дмитревская Павла Данииловна",
    "phone": "+7 (999) 000-00-00",
    "shortName": "Дмитревская Павла",
    "experienceYears": 6,
    "salesConversionRate": 80,
    "bio": "",
    "telegram": "@tutor",
    "color": "indigo",
    "rating": 4.95,
    "education": "",
    "achievements": [],
    "activeStudents": 0
  },
  {
    "salesConversionRate": 74,
    "avatar": "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150&auto=format&fit=crop&q=80",
    "subjects": [
      "Обществознание",
      "Право",
      "Экономика"
    ],
    "tag": "Эксперт ОГЭ/ЕГЭ",
    "education": "НИУ ВШЭ (Факультет права)",
    "color": "amber",
    "bio": "Юрист, помогает разобраться в сложнейших блоках «Право» и «Экономика».",
    "experienceYears": 6,
    "achievements": [
      "Подготовила призеров Всероссийской олимпиады школьников по праву",
      "Действующий эксперт региональной комиссии ЕГЭ",
      "95% учеников сдают ОГЭ на оценку «отлично»"
    ],
    "name": "Камиля Рустамовна Валиуллина",
    "rating": 4.92,
    "activeStudents": 11,
    "id": "tutor-3",
    "phone": "+7 (912) 345-67-83",
    "availableDays": [
      1,
      3,
      5,
      6
    ],
    "telegram": "@kamilya_soc",
    "shortName": "Камиля Валиуллина"
  },
  {
    "experienceYears": 5,
    "availableDays": [
      1,
      2,
      4,
      5
    ],
    "activeStudents": 9,
    "education": "МФТИ (Физтех), Факультет общей и прикладной физики",
    "rating": 4.95,
    "color": "cyan",
    "subjects": [
      "Физика",
      "Информатика (Python)",
      "ОГЭ/ЕГЭ"
    ],
    "salesConversionRate": 70,
    "tag": "Сложные темы",
    "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    "name": "Стрижкова Анастасия Сергеевна",
    "bio": "МФТИ, учит решать задачи без зубрежки формул — через понимание законов.",
    "telegram": "@anastasia_phys",
    "id": "tutor-5",
    "achievements": [
      "Призер олимпиады «Физтех» и Международной студенческой олимпиады",
      "Средний балл по физике среди учеников — 81.5",
      "Разработала интерактивный симулятор физических экспериментов"
    ],
    "shortName": "Анастасия Стрижкова",
    "phone": "+7 (912) 345-67-85"
  },
  {
    "subjects": [
      "История России",
      "Всемирная история",
      "ОГЭ/ЕГЭ"
    ],
    "activeStudents": 10,
    "name": "Барышева Любава Владимировна",
    "rating": 4.94,
    "phone": "+7 (912) 345-67-88",
    "salesConversionRate": 72,
    "avatar": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    "id": "tutor-8",
    "telegram": "@lyubava_hist",
    "bio": "Превращает историю в захватывающий сериал. Работа с картами и культурой на максимум.",
    "availableDays": [
      2,
      3,
      4,
      5,
      7
    ],
    "color": "orange",
    "shortName": "Любава Барышева",
    "tag": "История"
  },
  {
    "targetGrades": [
      "1-4",
      "5-8",
      "9",
      "10",
      "11"
    ],
    "id": "tutor-1791250636955",
    "rating": 5,
    "telegram": "@tutor",
    "shortName": "Max Navarro",
    "color": "indigo",
    "salesConversionRate": 80,
    "experienceYears": 6,
    "activeStudents": 0,
    "bio": "Practical, personalized training focused on real spoken English. Lessons built around the student’s actual goals (work, interviews, exams, daily confidence). Heavy emphasis on fluency, pronunciation, and using English under pressure. Business English specialty. No generic textbook courses — real-world scenarios and conversation.",
    "availableDays": [
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "targetGoals": [
      "ege",
      "oge",
      "olympiad",
      "grades"
    ],
    "avatar": "https://yellow-hornet-182036.hostingersite.com/hcgi/platform/api/files/pbc_1636847646/maxnavarro98976/g_h2l5_98s5cmr1ls.jpg",
    "name": "Max Navarro",
    "phone": "+7 (999) 000-00-00",
    "subjects": [
      "Математика (профиль)",
      "English Language"
    ],
    "achievements": []
  }
];

export const SUBJECT_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  'Математика (профиль)': { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
  'Алгебра': { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
  'Русский язык': { bg: 'bg-indigo-50', text: 'text-indigo-700', border: 'border-indigo-200' },
  'Литература': { bg: 'bg-indigo-50', text: 'text-indigo-700', border: 'border-indigo-200' },
  'Обществознание': { bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200' },
  'Английский язык': { bg: 'bg-rose-50', text: 'text-rose-700', border: 'border-rose-200' },
  'Физика': { bg: 'bg-cyan-50', text: 'text-cyan-700', border: 'border-cyan-200' },
  'Информатика': { bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
  'Химия': { bg: 'bg-violet-50', text: 'text-violet-700', border: 'border-violet-200' },
  'Биология': { bg: 'bg-teal-50', text: 'text-teal-700', border: 'border-teal-200' },
  'История': { bg: 'bg-orange-50', text: 'text-orange-700', border: 'border-orange-200' },
};

export function getInitialAppointments(): Appointment[] {
  const currentWeekStart = startOfWeek(new Date(), { weekStartsOn: 1 });
  const getDateStr = (dayOffset: number) => format(addDays(currentWeekStart, dayOffset), 'yyyy-MM-dd');

  return [
    // Понедельник
    {
      id: 'app-1',
      tutorId: 'tutor-1790419420798',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Максим Лебедев',
      parentPhone: '+7 (916) 123-45-01',
      parentName: 'Елена (мама)',
      grade: '11 класс (ЕГЭ Профиль)',
      subject: 'Русский язык',
      date: getDateStr(0),
      startTime: '11:00',
      endTime: '12:00',
      type: 'trial',
      status: 'confirmed',
      learningGoalCategory: 'ege',
      notes: 'Стереометрия, задача №14. Домашка проверена.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-14 09:30',
      managerName: 'Анна Ковалёва (Отдел продаж)',
      studentGoal: 'Цель: 82+ балла (бюджет Бауманки). Слабое место: стереометрия №14.',
      tutorNotes: 'Остановились на векторно-координатном методе для правильной призмы. Проверить пункт (б).',
      whiteboardUrl: 'https://sboard.online/board/math-lebedev-maxim',
      homework: {
        title: '3 задачи из ФИПИ на сечение пирамиды плоскостью',
        deadline: 'до пятницы 18:00',
        status: 'submitted',
        notes: 'Прислал фото решений в чат, разобрали 2 из 3',
        link: 'https://math-ege.sdamgia.ru/test?id=1234567',
      },
    },
    {
      id: 'app-olympiad-trial',
      tutorId: 'tutor-1790419420798',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Лев Романов',
      parentPhone: '+7 (926) 777-88-99',
      parentName: 'Виктория (мама)',
      grade: '10 класс',
      subject: 'Русский язык',
      date: getDateStr(0),
      startTime: '13:00',
      endTime: '14:00',
      type: 'trial',
      status: 'confirmed',
      learningGoalCategory: 'olympiad',
      studentGoal: 'Олимпиада «Высшая проба» и Всерос по математике (диплом)',
      notes: 'ВВОДНЫЙ УРОК: Подготовка к олимпиадам. Мама хочет проверить уровень и стратегию на диплом перечневой олимпиады.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-14 09:45',
      managerName: 'Анна Ковалёва (Отдел продаж)',
      quizContext: {
        gradeCategory: '10-11',
        targetScore: 'Олимпиады (Всерос, Перечневые, диплом)',
        currentGradeScore: 'Отличник, подготовка к олимпиадам/ЕГЭ 90+',
        primaryOffer: 'grant30',
        leadSource: 'Квиз-диагностика на sto-pyaterok.ru',
      },
    },
    {
      id: 'app-2',
      tutorId: 'tutor-1790419420798',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Алиса Воронова',
      parentPhone: '+7 (926) 998-11-22',
      parentName: 'Ольга Сергеевна',
      grade: '9 класс (ОГЭ)',
      subject: 'Русский язык',
      date: getDateStr(0),
      startTime: '18:00',
      endTime: '19:00',
      type: 'trial',
      status: 'confirmed',
      learningGoalCategory: 'oge',
      notes: 'ПЕРВЫЙ ПРОБНЫЙ УРОК! Мама хочет понять уровень геометрии.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-14 11:15',
      managerName: 'Сергей Морозов (Менеджер)',
      studentGoal: 'ОГЭ оценка «5». Страх перед геометрией во 2-й части (№23-24).',
      tutorNotes: 'План пробного: 10 мин знакомство + тест базы, 25 мин решение свойства хорд и секущих, 15 мин диагностика.',
      whiteboardUrl: 'https://sboard.online/board/math-voronova-trial',
      quizContext: {
        gradeCategory: '8-9',
        targetScore: 'ОГЭ на 5 (сдать вторую часть геометрии)',
        currentGradeScore: 'Тройка-четвёрка, плавает в теоремах',
        primaryOffer: 'grant30',
        leadSource: 'Квиз-диагностика на сайте sto-pyaterok.ru',
      },
      homework: {
        title: 'Тест самодиагностики из 5 вопросов',
        status: 'assigned',
        deadline: 'к следующему уроку',
      },
    },
    {
      id: 'app-3',
      tutorId: 'tutor-1790419420798',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Егор Смирнов',
      parentPhone: '+7 (903) 777-33-44',
      grade: '11 класс (ЕГЭ Профиль)',
      subject: 'Русский язык',
      date: getDateStr(0),
      startTime: '19:00',
      endTime: '20:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Параметры №18, повторение тригонометрии.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-12 14:00',
      managerName: 'Анна Ковалёва',
      studentGoal: 'Цель: 88+ баллов. Закрепить параметры и теорию чисел.',
      tutorNotes: 'Графический метод в плоскости (x; a). Дорешать случай касания параболы.',
      whiteboardUrl: 'https://sboard.online/board/math-smirnov-ege',
      homework: {
        title: 'Параметры №18: системы с модулем (5 задач)',
        deadline: 'до вторника 20:00',
        status: 'late',
        notes: 'Напомнить завтра утром!',
      },
    },
    {
      id: 'app-4',
      tutorId: 'tutor-4',
      tutorName: 'Блинова Татьяна Викторовна',
      studentName: 'София Миронова',
      parentPhone: '+7 (915) 333-22-11',
      grade: '10 класс',
      subject: 'Английский язык',
      date: getDateStr(0),
      startTime: '14:00',
      endTime: '15:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Speaking & Use of English. Level B2 target.',
      meetingUrl: 'https://zoom.us/j/100pyaterok_eng',
      createdAt: '2026-09-13 16:20',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-5',
      tutorId: 'tutor-4',
      tutorName: 'Блинова Татьяна Викторовна',
      studentName: 'Тимофей Казанцев',
      parentPhone: '+7 (918) 456-78-90',
      grade: '9 класс (ОГЭ)',
      subject: 'Английский язык',
      date: getDateStr(0),
      startTime: '15:00',
      endTime: '16:00',
      type: 'trial',
      status: 'confirmed',
      notes: 'Пробный урок. Хотят сдать ОГЭ на максимум (отличник).',
      meetingUrl: 'https://zoom.us/j/100pyaterok_eng',
      createdAt: '2026-09-14 10:00',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-6',
      tutorId: 'tutor-4',
      tutorName: 'Блинова Татьяна Викторовна',
      studentName: 'Артем Мельников',
      parentPhone: '+7 (925) 888-99-00',
      grade: '11 класс (ЕГЭ)',
      subject: 'Английский язык',
      date: getDateStr(0),
      startTime: '17:00',
      endTime: '18:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Разбор эссе по графикам (№38).',
      meetingUrl: 'https://zoom.us/j/100pyaterok_eng',
      createdAt: '2026-09-11 12:40',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-7',
      tutorId: 'tutor-6',
      tutorName: 'Сафаргалина Арина Владимировна',
      studentName: 'Ксения Попова',
      parentPhone: '+7 (905) 555-12-34',
      grade: '11 класс (Мед. вуз)',
      subject: 'Химия',
      date: getDateStr(0),
      startTime: '21:00',
      endTime: '22:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Органическая химия: спирты и альдегиды.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-chem',
      createdAt: '2026-09-13 18:10',
      managerName: 'Анна Ковалёва',
    },

    // Вторник
    {
      id: 'app-8',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Дарья Соколова',
      parentPhone: '+7 (916) 777-11-22',
      grade: '11 класс (ЕГЭ)',
      subject: 'Русский язык',
      date: getDateStr(1),
      startTime: '16:00',
      endTime: '17:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Сочинение ЕГЭ. Формулировка проблемы и комментарий.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-12 15:00',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-9',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Иван Кузнецов',
      parentPhone: '+7 (926) 333-44-55',
      grade: '9 класс (ОГЭ)',
      subject: 'Русский язык',
      date: getDateStr(1),
      startTime: '17:00',
      endTime: '18:00',
      type: 'trial',
      status: 'confirmed',
      notes: 'Пробный. Нужна подготовка к итоговому собеседованию.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-14 14:20',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-10',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Полина Васильева',
      parentPhone: '+7 (915) 111-22-33',
      grade: '11 класс',
      subject: 'Русский язык',
      date: getDateStr(1),
      startTime: '18:00',
      endTime: '19:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Тест ЕГЭ: задания 9-12 (орфография корней и суффиксов).',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-10 11:00',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-11',
      tutorId: 'tutor-1790419420798',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Матвей Ильин',
      parentPhone: '+7 (910) 999-88-77',
      grade: '10 класс',
      subject: 'Русский язык',
      date: getDateStr(1),
      startTime: '18:00',
      endTime: '19:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Тригонометрические уравнения и отбор корней.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-13 13:00',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-12',
      tutorId: 'tutor-1790419420798',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Виктория Громова',
      parentPhone: '+7 (903) 123-99-88',
      grade: '11 класс',
      subject: 'Русский язык',
      date: getDateStr(1),
      startTime: '19:00',
      endTime: '20:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Экономическая задача №16 (кредиты и вклады).',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-12 17:30',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-13',
      tutorId: 'tutor-6',
      tutorName: 'Сафаргалина Арина Владимировна',
      studentName: 'Никита Романов',
      parentPhone: '+7 (916) 444-55-66',
      grade: '11 класс',
      subject: 'Биология',
      date: getDateStr(1),
      startTime: '19:00',
      endTime: '20:00',
      type: 'trial',
      status: 'confirmed',
      notes: 'Пробный. Ученик хочет 90+ для поступления в мед.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-chem',
      createdAt: '2026-09-14 16:50',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-14',
      tutorId: 'tutor-6',
      tutorName: 'Сафаргалина Арина Владимировна',
      studentName: 'Олег Савельев',
      parentPhone: '+7 (926) 777-88-99',
      grade: '11 класс',
      subject: 'Химия',
      date: getDateStr(1),
      startTime: '21:00',
      endTime: '22:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Задачи №34 на смеси и атомистику.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-chem',
      createdAt: '2026-09-11 19:00',
      managerName: 'Сергей Морозов',
    },

    // Среда
    {
      id: 'app-15',
      tutorId: 'tutor-1790419420798',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Антон Белов',
      parentPhone: '+7 (915) 666-77-88',
      grade: '11 класс',
      subject: 'Русский язык',
      date: getDateStr(2),
      startTime: '11:00',
      endTime: '12:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Производная и первообразная в задании №8.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-10 12:00',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-16',
      tutorId: 'tutor-1790419420798',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Кристина Маркова',
      parentPhone: '+7 (917) 888-22-33',
      grade: '9 класс',
      subject: 'Русский язык',
      date: getDateStr(2),
      startTime: '12:00',
      endTime: '13:00',
      type: 'trial',
      status: 'confirmed',
      notes: 'Пробный. Боятся ОГЭ, оценка 3 в школе.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-14 15:40',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-17',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Мария Федорова',
      parentPhone: '+7 (925) 333-11-00',
      grade: '10 класс',
      subject: 'Русский язык',
      date: getDateStr(2),
      startTime: '17:00',
      endTime: '18:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Синтаксис сложного предложения.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-12 18:00',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-18',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Ярослав Ковалев',
      parentPhone: '+7 (916) 222-33-44',
      grade: '11 класс',
      subject: 'Русский язык',
      date: getDateStr(2),
      startTime: '18:00',
      endTime: '19:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Итоговое декабрьское сочинение: аргументы из классики.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-13 14:00',
      managerName: 'Сергей Морозов',
    },

    // Четверг
    {
      id: 'app-19',
      tutorId: 'tutor-1790419420798',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Денис Новиков',
      parentPhone: '+7 (903) 555-88-11',
      grade: '11 класс',
      subject: 'Русский язык',
      date: getDateStr(3),
      startTime: '11:00',
      endTime: '12:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Теория вероятностей сложная (№5).',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-11 16:00',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-20',
      tutorId: 'tutor-1790419420798',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Вероника Зайцева',
      parentPhone: '+7 (915) 999-00-11',
      grade: '10 класс',
      subject: 'Русский язык',
      date: getDateStr(3),
      startTime: '12:00',
      endTime: '13:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Неравенства метод интервалов.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-12 11:30',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-21',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Илья Тарасов',
      parentPhone: '+7 (926) 444-11-22',
      grade: '11 класс',
      subject: 'Русский язык',
      date: getDateStr(3),
      startTime: '15:00',
      endTime: '16:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Пунктуация: задания 16-21.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-13 12:00',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-22',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Анна Павлова',
      parentPhone: '+7 (916) 888-33-22',
      grade: '11 класс',
      subject: 'Русский язык',
      date: getDateStr(3),
      startTime: '16:00',
      endTime: '17:00',
      type: 'trial',
      status: 'confirmed',
      notes: 'Пробный урок. Девушка идет на золотую медаль.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-14 18:30',
      managerName: 'Сергей Морозов',
    },

    // Пятница
    {
      id: 'app-23',
      tutorId: 'tutor-1790419420798',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Степан Орлов',
      parentPhone: '+7 (918) 777-66-55',
      grade: '11 класс',
      subject: 'Русский язык',
      date: getDateStr(4),
      startTime: '12:00',
      endTime: '13:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Планиметрия №17, окружности и касательные.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-10 17:00',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-24',
      tutorId: 'tutor-4',
      tutorName: 'Блинова Татьяна Викторовна',
      studentName: 'Полина Семенова',
      parentPhone: '+7 (925) 123-77-88',
      grade: '8 класс',
      subject: 'Английский язык',
      date: getDateStr(4),
      startTime: '14:00',
      endTime: '15:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Past Perfect vs Past Simple, грамматический тренажер.',
      meetingUrl: 'https://zoom.us/j/100pyaterok_eng',
      createdAt: '2026-09-12 16:40',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-25',
      tutorId: 'tutor-4',
      tutorName: 'Блинова Татьяна Викторовна',
      studentName: 'Роман Власов',
      parentPhone: '+7 (916) 555-44-33',
      grade: '11 класс',
      subject: 'Английский язык',
      date: getDateStr(4),
      startTime: '16:00',
      endTime: '17:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Устная часть ЕГЭ: описание картинок и диалог-интервью.',
      meetingUrl: 'https://zoom.us/j/100pyaterok_eng',
      createdAt: '2026-09-11 14:15',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-26',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Арсений Борисов',
      parentPhone: '+7 (903) 222-11-00',
      grade: '11 класс',
      subject: 'Русский язык',
      date: getDateStr(4),
      startTime: '18:00',
      endTime: '19:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Анализ текста, поиск авторской позиции.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-13 15:50',
      managerName: 'Сергей Морозов',
    },

    // Суббота
    {
      id: 'app-27',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Владислав Морозов',
      parentPhone: '+7 (915) 000-88-99',
      grade: '9 класс',
      subject: 'Русский язык',
      date: getDateStr(5),
      startTime: '10:00',
      endTime: '11:00',
      type: 'trial',
      status: 'confirmed',
      notes: 'Пробный урок. Подготовка к ОГЭ.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-14 17:10',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-28',
      tutorId: 'tutor-4',
      tutorName: 'Блинова Татьяна Викторовна',
      studentName: 'Анастасия Лукина',
      parentPhone: '+7 (926) 111-99-00',
      grade: '10 класс',
      subject: 'Английский язык',
      date: getDateStr(5),
      startTime: '15:00',
      endTime: '16:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Подготовка к олимпиадам «Ломоносов» и ВсОШ.',
      meetingUrl: 'https://zoom.us/j/100pyaterok_eng',
      createdAt: '2026-09-12 10:20',
      managerName: 'Сергей Морозов',
    },
  ];
}

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'Новая запись на пробный урок',
    message: 'Менеджер Анна записала ученика Максима Лебедева к Диане Рубцовой на сегодня 11:00',
    time: '5 минут назад',
    type: 'booking',
    read: false,
    tutorId: 'tutor-1790419420798',
  },
  {
    id: 'notif-2',
    title: 'Клиент подтвердил занятие',
    message: 'Родитель Алисы Вороновой подтвердил пробный урок на сегодня 18:00',
    time: '25 минут назад',
    type: 'booking',
    read: false,
    tutorId: 'tutor-1790419420798',
  },
  {
    id: 'notif-3',
    title: 'Открыто свободное окно',
    message: 'Татьяна Блинова добавила доступный слот: Пятница 16:00 - 17:00',
    time: '1 час назад',
    type: 'reminder',
    read: true,
    tutorId: 'tutor-4',
  },
  {
    id: 'notif-4',
    title: 'Синхронизация с календарем',
    message: 'Все 28 уроков недели успешно синхронизированы с календарями преподавателей',
    time: '3 часа назад',
    type: 'reminder',
    read: true,
  },
];
