import { Tutor, Appointment, AppNotification, Manager } from './types';
import { format, startOfWeek, addDays } from 'date-fns';

export const INITIAL_MANAGERS: Manager[] = [
  {
    id: 'mgr-admin',
    name: 'Руководитель школы (Администратор)',
    email: 'admin@sto-pyaterok.ru',
    phone: '+7 (999) 111-22-33',
    role: 'admin',
    active: true,
    createdAt: '2025-01-10',
  },
  {
    id: 'mgr-1',
    name: 'Елена Васильева',
    email: 'elena@sto-pyaterok.ru',
    phone: '+7 (926) 400-12-34',
    role: 'manager',
    active: true,
    createdAt: '2025-09-01',
  },
  {
    id: 'mgr-2',
    name: 'Михаил Соколов',
    email: 'mikhail@sto-pyaterok.ru',
    phone: '+7 (926) 500-56-78',
    role: 'manager',
    active: true,
    createdAt: '2025-11-15',
  },
];

export const TUTORS: Tutor[] = [
  {
    id: 'tutor-1',
    name: 'Диана Сергеевна Рубцова',
    shortName: 'Диана Рубцова',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    subjects: ['Математика (профиль)', 'ОГЭ/ЕГЭ', 'Алгебра'],
    color: 'emerald',
    phone: '+7 (912) 345-67-81',
    telegram: '@diana_math',
    rating: 4.96,
    activeStudents: 14,
    availableDays: [1, 2, 3, 4, 5],
    bio: 'Эксперт ЕГЭ с 7-летним стажем. Средний балл выпускников — 84+.',
    salesConversionRate: 84,
    tag: 'Топ продаж 🔥',
    education: 'МГУ им. М.В. Ломоносова (Мехмат)',
    experienceYears: 7,
    hourlyRate: 2400,
    achievements: [
      'Подготовила 14 стобалльников ЕГЭ по профильной математике',
      'Эксперт предметной комиссии по проверке развернутых ответов ЕГЭ',
      'Победитель олимпиады учителей математики «Профи-2023»',
      'Автор методики разбора экономической задачи №16 за 12 минут'
    ],
    preferredBreakMinutes: 10,
    maxDailyLessons: 5,
    defaultWhiteboardUrl: 'https://sboard.online/board/math-diana',
    isPausedToday: false,
  },
  {
    id: 'tutor-2',
    name: 'Асият Асхатовна Шаваева',
    shortName: 'Асият Шаваева',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    subjects: ['Русский язык', 'Литература', 'Сочинение ЕГЭ'],
    color: 'indigo',
    phone: '+7 (912) 345-67-82',
    telegram: '@asiyat_rus',
    rating: 4.98,
    activeStudents: 18,
    availableDays: [2, 3, 4, 5, 6],
    bio: 'Филолог, автор методики ускоренной подготовки к тестовой части за 2 месяца.',
    salesConversionRate: 88,
    tag: 'Лидер доходимости ⭐',
    education: 'СПбГУ, Филологический факультет, красный диплом',
    experienceYears: 9,
    hourlyRate: 2200,
    achievements: [
      'Средний балл учеников по русскому языку в 2025 году — 89.2',
      '22 ученика сдали ЕГЭ на 95+ баллов',
      'Разработчик интенсива по идеальному сочинению (критерий К1-К12 на 100%)',
      'Финалист всероссийского конкурса «Педагогический дебют»'
    ],
  },
  {
    id: 'tutor-3',
    name: 'Камиля Рустамовна Валиуллина',
    shortName: 'Камиля Валиуллина',
    avatar: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150&auto=format&fit=crop&q=80',
    subjects: ['Обществознание', 'Право', 'Экономика'],
    color: 'amber',
    phone: '+7 (912) 345-67-83',
    telegram: '@kamilya_soc',
    rating: 4.92,
    activeStudents: 11,
    availableDays: [1, 3, 5, 6],
    bio: 'Юрист, помогает разобраться в сложнейших блоках «Право» и «Экономика».',
    salesConversionRate: 74,
    tag: 'Эксперт ОГЭ/ЕГЭ',
    education: 'НИУ ВШЭ (Факультет права)',
    experienceYears: 6,
    hourlyRate: 2000,
    achievements: [
      'Подготовила призеров Всероссийской олимпиады школьников по праву',
      'Действующий эксперт региональной комиссии ЕГЭ',
      '95% учеников сдают ОГЭ на оценку «отлично»'
    ],
  },
  {
    id: 'tutor-4',
    name: 'Блинова Татьяна Викторовна',
    shortName: 'Татьяна Блинова',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    subjects: ['Английский язык', 'ОГЭ/ЕГЭ', 'Разговорный'],
    color: 'rose',
    phone: '+7 (912) 345-67-84',
    telegram: '@tatiana_eng',
    rating: 5.0,
    activeStudents: 16,
    availableDays: [1, 2, 3, 4, 5, 6],
    bio: 'Сертификат CELTA, кембриджские методики, снятие языкового барьера.',
    salesConversionRate: 82,
    tag: 'Топ конверсий 🔥',
    education: 'МГЛУ им. Мориса Тореза, Международный сертификат Cambridge CELTA',
    experienceYears: 11,
    hourlyRate: 2600,
    achievements: [
      'Сертификат Cambridge CELTA Grade A (преподавание международного уровня)',
      '18 учеников поступили в зарубежные и топовые российские вузы (МГИМО, ВШЭ)',
      'Автор курса преодоления языкового барьера для подростков'
    ],
  },
  {
    id: 'tutor-5',
    name: 'Стрижкова Анастасия Сергеевна',
    shortName: 'Анастасия Стрижкова',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    subjects: ['Физика', 'Информатика (Python)', 'ОГЭ/ЕГЭ'],
    color: 'cyan',
    phone: '+7 (912) 345-67-85',
    telegram: '@anastasia_phys',
    rating: 4.95,
    activeStudents: 9,
    availableDays: [1, 2, 4, 5],
    bio: 'МФТИ, учит решать задачи без зубрежки формул — через понимание законов.',
    salesConversionRate: 70,
    tag: 'Сложные темы',
    education: 'МФТИ (Физтех), Факультет общей и прикладной физики',
    experienceYears: 5,
    hourlyRate: 2300,
    achievements: [
      'Призер олимпиады «Физтех» и Международной студенческой олимпиады',
      'Средний балл по физике среди учеников — 81.5',
      'Разработала интерактивный симулятор физических экспериментов'
    ],
  },
  {
    id: 'tutor-6',
    name: 'Сафаргалина Арина Владимировна',
    shortName: 'Арина Сафаргалина',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    subjects: ['Химия', 'Биология', 'Медицинские классы'],
    color: 'violet',
    phone: '+7 (912) 345-67-86',
    telegram: '@arina_chem',
    rating: 4.97,
    activeStudents: 15,
    availableDays: [1, 2, 3, 4, 5, 7],
    bio: 'Подготовка в ведущие медвузы страны (Сеченовка, Пирогова). Разбор органики на пальцах.',
    salesConversionRate: 86,
    tag: 'Медвузы / Чек 💎',
    education: 'Первый МГМУ им. И.М. Сеченова, Кандидат биологических наук',
    experienceYears: 8,
    hourlyRate: 2500,
    achievements: [
      'Кандидат биологических наук, автор 12 научных публикаций',
      'Более 50 выпускников обучаются на бюджете в Первом Меде и РНИМУ им. Пирогова',
      'Победитель гранта молодым ученым-преподавателям'
    ],
  },
  {
    id: 'tutor-7',
    name: 'Абдулгужина Оксана Михайловна',
    shortName: 'Оксана Абдулгужина',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    subjects: ['Математика (база)', 'Начальная школа', '5-9 класс'],
    color: 'sky',
    phone: '+7 (912) 345-67-87',
    telegram: '@oxana_math',
    rating: 4.89,
    activeStudents: 12,
    availableDays: [1, 2, 3, 5, 6],
    bio: 'Педагог высшей категории. Устраняет пробелы в программе, вселяет уверенность в ребенка.',
    salesConversionRate: 78,
    tag: 'Началка & База',
    education: 'МПГУ, Педагогическое образование, Высшая квалификационная категория',
    experienceYears: 14,
    hourlyRate: 1900,
    achievements: [
      'Почетный работник общего образования, высшая категория',
      'Автор пособия «Понятная геометрия для 7-9 классов без слез»',
      '100% положительных отзывов родителей за 5 лет работы в онлайн'
    ],
  },
  {
    id: 'tutor-8',
    name: 'Барышева Любава Владимировна',
    shortName: 'Любава Барышева',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    subjects: ['История России', 'Всемирная история', 'ОГЭ/ЕГЭ'],
    color: 'orange',
    phone: '+7 (912) 345-67-88',
    telegram: '@lyubava_hist',
    rating: 4.94,
    activeStudents: 10,
    availableDays: [2, 3, 4, 5, 7],
    bio: 'Превращает историю в захватывающий сериал. Работа с картами и культурой на максимум.',
    salesConversionRate: 72,
    tag: 'История',
  },
];

export const SUBJECT_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  'Математика (профиль)': { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
  'Алгебра': { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
  'Русский язык': { bg: 'bg-indigo-50', text: 'text-indigo-700', border: 'border-indigo-200' },
  'Литература': { bg: 'bg-indigo-50', text: 'text-indigo-700', border: 'border-indigo-200' },
  'Обществознание': { bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200' },
  'Английский язык': { bg: 'bg-rose-50', text: 'text-rose-700', border: 'border-rose-200' },
  'Физика': { bg: 'bg-cyan-50', text: 'text-cyan-700', border: 'border-cyan-200' },
  'Информатика': { bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
  'Химия': { bg: 'bg-violet-50', text: 'text-violet-700', border: 'border-violet-200' },
  'Биология': { bg: 'bg-teal-50', text: 'text-teal-700', border: 'border-teal-200' },
  'История': { bg: 'bg-orange-50', text: 'text-orange-700', border: 'border-orange-200' },
};

export function getInitialAppointments(): Appointment[] {
  const currentWeekStart = startOfWeek(new Date(), { weekStartsOn: 1 });
  const getDateStr = (dayOffset: number) => format(addDays(currentWeekStart, dayOffset), 'yyyy-MM-dd');

  return [
    // Понедельник
    {
      id: 'app-1',
      tutorId: 'tutor-1',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Максим Лебедев',
      parentPhone: '+7 (916) 123-45-01',
      parentName: 'Елена (мама)',
      grade: '11 класс (ЕГЭ Профиль)',
      subject: 'Математика (профиль)',
      date: getDateStr(0),
      startTime: '11:00',
      endTime: '12:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Стереометрия, задача №14. Домашка проверена.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-14 09:30',
      managerName: 'Анна Ковалёва (Отдел продаж)',
      studentGoal: 'Цель: 82+ балла (бюджет Бауманки). Слабое место: стереометрия №14.',
      tutorNotes: 'Остановились на векторно-координатном методе для правильной призмы. Проверить пункт (б).',
      whiteboardUrl: 'https://sboard.online/board/math-lebedev-maxim',
      homework: {
        title: '3 задачи из ФИПИ на сечение пирамиды плоскостью',
        deadline: 'до пятницы 18:00',
        status: 'submitted',
        notes: 'Прислал фото решений в чат, разобрали 2 из 3',
        link: 'https://math-ege.sdamgia.ru/test?id=1234567',
      },
    },
    {
      id: 'app-2',
      tutorId: 'tutor-1',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Алиса Воронова',
      parentPhone: '+7 (926) 998-11-22',
      parentName: 'Ольга Сергеевна',
      grade: '9 класс (ОГЭ)',
      subject: 'Математика (профиль)',
      date: getDateStr(0),
      startTime: '18:00',
      endTime: '19:00',
      type: 'trial',
      status: 'confirmed',
      notes: 'ПЕРВЫЙ ПРОБНЫЙ УРОК! Мама хочет понять уровень геометрии.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-14 11:15',
      managerName: 'Сергей Морозов (Менеджер)',
      studentGoal: 'ОГЭ оценка «5». Страх перед геометрией во 2-й части (№23-24).',
      tutorNotes: 'План пробного: 10 мин знакомство + тест базы, 25 мин решение свойства хорд и секущих, 15 мин диагностика.',
      whiteboardUrl: 'https://sboard.online/board/math-voronova-trial',
      quizContext: {
        gradeCategory: '8-9',
        targetScore: 'ОГЭ на 5 (сдать вторую часть геометрии)',
        currentGradeScore: 'Тройка-четвёрка, плавает в теоремах',
        primaryOffer: 'grant30',
        leadSource: 'Квиз-диагностика на сайте sto-pyaterok.ru',
      },
      homework: {
        title: 'Тест самодиагностики из 5 вопросов',
        status: 'assigned',
        deadline: 'к следующему уроку',
      },
    },
    {
      id: 'app-3',
      tutorId: 'tutor-1',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Егор Смирнов',
      parentPhone: '+7 (903) 777-33-44',
      grade: '11 класс (ЕГЭ Профиль)',
      subject: 'Математика (профиль)',
      date: getDateStr(0),
      startTime: '19:00',
      endTime: '20:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Параметры №18, повторение тригонометрии.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-12 14:00',
      managerName: 'Анна Ковалёва',
      studentGoal: 'Цель: 88+ баллов. Закрепить параметры и теорию чисел.',
      tutorNotes: 'Графический метод в плоскости (x; a). Дорешать случай касания параболы.',
      whiteboardUrl: 'https://sboard.online/board/math-smirnov-ege',
      homework: {
        title: 'Параметры №18: системы с модулем (5 задач)',
        deadline: 'до вторника 20:00',
        status: 'late',
        notes: 'Напомнить завтра утром!',
      },
    },
    {
      id: 'app-4',
      tutorId: 'tutor-4',
      tutorName: 'Блинова Татьяна Викторовна',
      studentName: 'София Миронова',
      parentPhone: '+7 (915) 333-22-11',
      grade: '10 класс',
      subject: 'Английский язык',
      date: getDateStr(0),
      startTime: '14:00',
      endTime: '15:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Speaking & Use of English. Level B2 target.',
      meetingUrl: 'https://zoom.us/j/100pyaterok_eng',
      createdAt: '2026-09-13 16:20',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-5',
      tutorId: 'tutor-4',
      tutorName: 'Блинова Татьяна Викторовна',
      studentName: 'Тимофей Казанцев',
      parentPhone: '+7 (918) 456-78-90',
      grade: '9 класс (ОГЭ)',
      subject: 'Английский язык',
      date: getDateStr(0),
      startTime: '15:00',
      endTime: '16:00',
      type: 'trial',
      status: 'confirmed',
      notes: 'Пробный урок. Хотят сдать ОГЭ на максимум (отличник).',
      meetingUrl: 'https://zoom.us/j/100pyaterok_eng',
      createdAt: '2026-09-14 10:00',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-6',
      tutorId: 'tutor-4',
      tutorName: 'Блинова Татьяна Викторовна',
      studentName: 'Артем Мельников',
      parentPhone: '+7 (925) 888-99-00',
      grade: '11 класс (ЕГЭ)',
      subject: 'Английский язык',
      date: getDateStr(0),
      startTime: '17:00',
      endTime: '18:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Разбор эссе по графикам (№38).',
      meetingUrl: 'https://zoom.us/j/100pyaterok_eng',
      createdAt: '2026-09-11 12:40',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-7',
      tutorId: 'tutor-6',
      tutorName: 'Сафаргалина Арина Владимировна',
      studentName: 'Ксения Попова',
      parentPhone: '+7 (905) 555-12-34',
      grade: '11 класс (Мед. вуз)',
      subject: 'Химия',
      date: getDateStr(0),
      startTime: '21:00',
      endTime: '22:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Органическая химия: спирты и альдегиды.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-chem',
      createdAt: '2026-09-13 18:10',
      managerName: 'Анна Ковалёва',
    },

    // Вторник
    {
      id: 'app-8',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Дарья Соколова',
      parentPhone: '+7 (916) 777-11-22',
      grade: '11 класс (ЕГЭ)',
      subject: 'Русский язык',
      date: getDateStr(1),
      startTime: '16:00',
      endTime: '17:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Сочинение ЕГЭ. Формулировка проблемы и комментарий.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-12 15:00',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-9',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Иван Кузнецов',
      parentPhone: '+7 (926) 333-44-55',
      grade: '9 класс (ОГЭ)',
      subject: 'Русский язык',
      date: getDateStr(1),
      startTime: '17:00',
      endTime: '18:00',
      type: 'trial',
      status: 'confirmed',
      notes: 'Пробный. Нужна подготовка к итоговому собеседованию.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-14 14:20',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-10',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Полина Васильева',
      parentPhone: '+7 (915) 111-22-33',
      grade: '11 класс',
      subject: 'Русский язык',
      date: getDateStr(1),
      startTime: '18:00',
      endTime: '19:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Тест ЕГЭ: задания 9-12 (орфография корней и суффиксов).',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-10 11:00',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-11',
      tutorId: 'tutor-1',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Матвей Ильин',
      parentPhone: '+7 (910) 999-88-77',
      grade: '10 класс',
      subject: 'Математика (профиль)',
      date: getDateStr(1),
      startTime: '18:00',
      endTime: '19:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Тригонометрические уравнения и отбор корней.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-13 13:00',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-12',
      tutorId: 'tutor-1',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Виктория Громова',
      parentPhone: '+7 (903) 123-99-88',
      grade: '11 класс',
      subject: 'Математика (профиль)',
      date: getDateStr(1),
      startTime: '19:00',
      endTime: '20:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Экономическая задача №16 (кредиты и вклады).',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-12 17:30',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-13',
      tutorId: 'tutor-6',
      tutorName: 'Сафаргалина Арина Владимировна',
      studentName: 'Никита Романов',
      parentPhone: '+7 (916) 444-55-66',
      grade: '11 класс',
      subject: 'Биология',
      date: getDateStr(1),
      startTime: '19:00',
      endTime: '20:00',
      type: 'trial',
      status: 'confirmed',
      notes: 'Пробный. Ученик хочет 90+ для поступления в мед.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-chem',
      createdAt: '2026-09-14 16:50',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-14',
      tutorId: 'tutor-6',
      tutorName: 'Сафаргалина Арина Владимировна',
      studentName: 'Олег Савельев',
      parentPhone: '+7 (926) 777-88-99',
      grade: '11 класс',
      subject: 'Химия',
      date: getDateStr(1),
      startTime: '21:00',
      endTime: '22:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Задачи №34 на смеси и атомистику.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-chem',
      createdAt: '2026-09-11 19:00',
      managerName: 'Сергей Морозов',
    },

    // Среда
    {
      id: 'app-15',
      tutorId: 'tutor-1',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Антон Белов',
      parentPhone: '+7 (915) 666-77-88',
      grade: '11 класс',
      subject: 'Математика (профиль)',
      date: getDateStr(2),
      startTime: '11:00',
      endTime: '12:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Производная и первообразная в задании №8.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-10 12:00',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-16',
      tutorId: 'tutor-1',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Кристина Маркова',
      parentPhone: '+7 (917) 888-22-33',
      grade: '9 класс',
      subject: 'Математика (профиль)',
      date: getDateStr(2),
      startTime: '12:00',
      endTime: '13:00',
      type: 'trial',
      status: 'confirmed',
      notes: 'Пробный. Боятся ОГЭ, оценка 3 в школе.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-14 15:40',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-17',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Мария Федорова',
      parentPhone: '+7 (925) 333-11-00',
      grade: '10 класс',
      subject: 'Русский язык',
      date: getDateStr(2),
      startTime: '17:00',
      endTime: '18:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Синтаксис сложного предложения.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-12 18:00',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-18',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Ярослав Ковалев',
      parentPhone: '+7 (916) 222-33-44',
      grade: '11 класс',
      subject: 'Русский язык',
      date: getDateStr(2),
      startTime: '18:00',
      endTime: '19:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Итоговое декабрьское сочинение: аргументы из классики.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-13 14:00',
      managerName: 'Сергей Морозов',
    },

    // Четверг
    {
      id: 'app-19',
      tutorId: 'tutor-1',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Денис Новиков',
      parentPhone: '+7 (903) 555-88-11',
      grade: '11 класс',
      subject: 'Математика (профиль)',
      date: getDateStr(3),
      startTime: '11:00',
      endTime: '12:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Теория вероятностей сложная (№5).',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-11 16:00',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-20',
      tutorId: 'tutor-1',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Вероника Зайцева',
      parentPhone: '+7 (915) 999-00-11',
      grade: '10 класс',
      subject: 'Математика (профиль)',
      date: getDateStr(3),
      startTime: '12:00',
      endTime: '13:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Неравенства метод интервалов.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-12 11:30',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-21',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Илья Тарасов',
      parentPhone: '+7 (926) 444-11-22',
      grade: '11 класс',
      subject: 'Русский язык',
      date: getDateStr(3),
      startTime: '15:00',
      endTime: '16:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Пунктуация: задания 16-21.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-13 12:00',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-22',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Анна Павлова',
      parentPhone: '+7 (916) 888-33-22',
      grade: '11 класс',
      subject: 'Русский язык',
      date: getDateStr(3),
      startTime: '16:00',
      endTime: '17:00',
      type: 'trial',
      status: 'confirmed',
      notes: 'Пробный урок. Девушка идет на золотую медаль.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-14 18:30',
      managerName: 'Сергей Морозов',
    },

    // Пятница
    {
      id: 'app-23',
      tutorId: 'tutor-1',
      tutorName: 'Диана Сергеевна Рубцова',
      studentName: 'Степан Орлов',
      parentPhone: '+7 (918) 777-66-55',
      grade: '11 класс',
      subject: 'Математика (профиль)',
      date: getDateStr(4),
      startTime: '12:00',
      endTime: '13:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Планиметрия №17, окружности и касательные.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-pyaterok-math',
      createdAt: '2026-09-10 17:00',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-24',
      tutorId: 'tutor-4',
      tutorName: 'Блинова Татьяна Викторовна',
      studentName: 'Полина Семенова',
      parentPhone: '+7 (925) 123-77-88',
      grade: '8 класс',
      subject: 'Английский язык',
      date: getDateStr(4),
      startTime: '14:00',
      endTime: '15:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Past Perfect vs Past Simple, грамматический тренажер.',
      meetingUrl: 'https://zoom.us/j/100pyaterok_eng',
      createdAt: '2026-09-12 16:40',
      managerName: 'Сергей Морозов',
    },
    {
      id: 'app-25',
      tutorId: 'tutor-4',
      tutorName: 'Блинова Татьяна Викторовна',
      studentName: 'Роман Власов',
      parentPhone: '+7 (916) 555-44-33',
      grade: '11 класс',
      subject: 'Английский язык',
      date: getDateStr(4),
      startTime: '16:00',
      endTime: '17:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Устная часть ЕГЭ: описание картинок и диалог-интервью.',
      meetingUrl: 'https://zoom.us/j/100pyaterok_eng',
      createdAt: '2026-09-11 14:15',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-26',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Арсений Борисов',
      parentPhone: '+7 (903) 222-11-00',
      grade: '11 класс',
      subject: 'Русский язык',
      date: getDateStr(4),
      startTime: '18:00',
      endTime: '19:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Анализ текста, поиск авторской позиции.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-13 15:50',
      managerName: 'Сергей Морозов',
    },

    // Суббота
    {
      id: 'app-27',
      tutorId: 'tutor-2',
      tutorName: 'Асият Асхатовна Шаваева',
      studentName: 'Владислав Морозов',
      parentPhone: '+7 (915) 000-88-99',
      grade: '9 класс',
      subject: 'Русский язык',
      date: getDateStr(5),
      startTime: '10:00',
      endTime: '11:00',
      type: 'trial',
      status: 'confirmed',
      notes: 'Пробный урок. Подготовка к ОГЭ.',
      meetingUrl: 'https://telemost.yandex.ru/j/100-rus',
      createdAt: '2026-09-14 17:10',
      managerName: 'Анна Ковалёва',
    },
    {
      id: 'app-28',
      tutorId: 'tutor-4',
      tutorName: 'Блинова Татьяна Викторовна',
      studentName: 'Анастасия Лукина',
      parentPhone: '+7 (926) 111-99-00',
      grade: '10 класс',
      subject: 'Английский язык',
      date: getDateStr(5),
      startTime: '15:00',
      endTime: '16:00',
      type: 'regular',
      status: 'confirmed',
      notes: 'Подготовка к олимпиадам «Ломоносов» и ВсОШ.',
      meetingUrl: 'https://zoom.us/j/100pyaterok_eng',
      createdAt: '2026-09-12 10:20',
      managerName: 'Сергей Морозов',
    },
  ];
}

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'Новая запись на пробный урок',
    message: 'Менеджер Анна записала ученика Максима Лебедева к Диане Рубцовой на сегодня 11:00',
    time: '5 минут назад',
    type: 'booking',
    read: false,
    tutorId: 'tutor-1',
  },
  {
    id: 'notif-2',
    title: 'Клиент подтвердил занятие',
    message: 'Родитель Алисы Вороновой подтвердил пробный урок на сегодня 18:00',
    time: '25 минут назад',
    type: 'booking',
    read: false,
    tutorId: 'tutor-1',
  },
  {
    id: 'notif-3',
    title: 'Открыто свободное окно',
    message: 'Татьяна Блинова добавила доступный слот: Пятница 16:00 - 17:00',
    time: '1 час назад',
    type: 'reminder',
    read: true,
    tutorId: 'tutor-4',
  },
  {
    id: 'notif-4',
    title: 'Синхронизация с календарем',
    message: 'Все 28 уроков недели успешно синхронизированы с календарями преподавателей',
    time: '3 часа назад',
    type: 'reminder',
    read: true,
  },
];
